# Python Numpy Practice Questions Answers

**1) Write a Python code which finds common values between two arrays by using for loop and if statement? **

In [1]:
import numpy as np

In [2]:
x1 = np.array([2,4,2,3,1,5])
x2 = np.array([5,8,1,2,6,7,2])

In [3]:
# Here, ravel() function helps in flatten the multidimensional array into 
# one dimensional array hence will be helpful in comparing the arrays.
a = x1.ravel()
b = x2.ravel()

In [4]:
# Below code will check common values in two arrays (one dimensional or multidimensional) 
# and return the unique common values.
# For example: in above arrays, value 2 is two times in both the arrays,
# so I will record it one time only in output.
commonVal = []
len_a = len(a)
len_b = len(b)
if len_a > len_b:
    for vl in b:
        if (vl in a) & (not vl in commonVal):
                commonVal.append(vl)
elif len_b > len_a:
    for vl in a:
        if (vl in b) & (not vl in commonVal):
                commonVal.append(vl)
elif len_a == len_b:
    for vl in a:
        if (vl in b) & (not vl in commonVal):
                commonVal.append(vl)

if len(commonVal) > 0:
    commonVal.sort()
    print("Common values are : {}".format(commonVal))
elif len(commonVal) == 0:
    print("No common values found.")

Common values are : [1, 2, 5]


**Testing above code for finding common values in two dimensional array**

In [5]:
x3=np.array([ [6, 7, 2, 4],
[7, 6, 8, 8],
[1, 6, 7, 7]])

x4=np.array([ [3, 5, 2, 4],
[7, 6, 5, 8],
[1, 6, 9, 7]])

In [6]:
a = x3.ravel()
b = x4.ravel()

In [7]:
commonVal = []
len_a = len(a)
len_b = len(b)
if len_a > len_b:
    for vl in b:
        if (vl in a) & (not vl in commonVal):
                commonVal.append(vl)
elif len_b > len_a:
    for vl in a:
        if (vl in b) & (not vl in commonVal):
                commonVal.append(vl)
elif len_a == len_b:
    for vl in a:
        if (vl in b) & (not vl in commonVal):
                commonVal.append(vl)

if len(commonVal) > 0:
    commonVal.sort()
    print("Common values are : {}".format(commonVal))
elif len(commonVal) == 0:
    print("No common values found.")

Common values are : [1, 2, 4, 6, 7, 8]


**2)  Create a random 5 by 5 matrix and replace the maximum value by 0 ? (Use for loop, first obtain the row by searching all of the elements in the rows and find the columns in a same way). Do not use the existing codes, produce your own code!!**

**Creating a random 5 by 5 matrix**

In [9]:
np.random.seed(1)
mtx = np.random.randint(25, size = (5,5))
mtx

array([[ 5, 11, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 13,  6],
       [18, 20,  5, 18, 20],
       [11, 10, 14, 18,  4]])

**Replacing max value in each Row with 0**

In [10]:
k = -1
m = -1
for i in range(0,np.shape(mtx)[0]):
    for j in mtx[i]:
        k +=1
        if (j == mtx[i].max()) & (j >= m):
            m = mtx[i,k]
            mtx[i,k] = 0
    m = -1
    k = -1
mtx

array([[ 5, 11,  0,  8,  9],
       [11,  5, 15,  0,  0],
       [ 1, 12,  7,  0,  6],
       [18,  0,  5, 18,  0],
       [11, 10, 14,  0,  4]])

**Creating a random 5 by 5 matrix**

In [11]:
np.random.seed(1)
mtx = np.random.randint(25, size = (5,5))
mtx

array([[ 5, 11, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 13,  6],
       [18, 20,  5, 18, 20],
       [11, 10, 14, 18,  4]])

**Replacing max value in each Column with 0**

In [12]:
k = -1
m = -1
for i in range(0,np.shape(mtx)[1]):
    for j in mtx[:,i]:
        k +=1
        if (j == mtx[:,i].max()) & (j >= m):
            m = mtx[k,i]
            mtx[k,i] = 0
    m = -1
    k = -1
mtx

array([[ 5, 11, 12,  8,  9],
       [11,  5,  0,  0, 16],
       [ 1, 12,  7, 13,  6],
       [ 0,  0,  5,  0,  0],
       [11, 10, 14,  0,  4]])

**Creating a random 5 by 5 matrix**

In [13]:
np.random.seed(1)
mtx = np.random.randint(25, size = (5,5))
mtx

array([[ 5, 11, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 13,  6],
       [18, 20,  5, 18, 20],
       [11, 10, 14, 18,  4]])

**Replacing max value in each Row and Column with 0**

In [14]:
# replacing max value in each row with 0
k = -1
m = -1
for i in range(0,np.shape(mtx)[0]):
    for j in mtx[i]:
        k +=1
        if (j == mtx[i].max()) & (j >= m):
            m = mtx[i,k]
            mtx[i,k] = 0
    m = -1
    k = -1
# replacing max value in each column with 0
k = -1
m = -1
for i in range(0,np.shape(mtx)[1]):
    for j in mtx[:,i]:
        k +=1
        if (j == mtx[:,i].max()) & (j >= m):
            m = mtx[k,i]
            mtx[k,i] = 0
    m = -1
    k = -1

mtx

array([[ 5, 11,  0,  8,  0],
       [11,  5,  0,  0,  0],
       [ 1,  0,  7,  0,  6],
       [ 0,  0,  5,  0,  0],
       [11, 10, 14,  0,  4]])

**3) Given two arrays X and Y with sizes 6 and 8, construct the matrix C such that Cij =1/(xi - yj). (Use for loop for this problem)?**

In [15]:
# np.random.seed(8)
# X = np.random.randint(10, size=6)
# Y = np.random.randint(10, size=8)
# OR
X = np.array([1,2,4,1,6,8])
print("Size of X: {}".format(len(X)))
Y = np.array([5,4,3,2,8,4,7,2])
print("Size of Y: {}".format(len(Y)))

Size of X: 6
Size of Y: 8


In [16]:
# Creating a zero matrix of 6 by 8
C = np.zeros((6,8))
C

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
import warnings; warnings.simplefilter('ignore')

# The above line is to ignore divide by zero warning.

for i in range(0,len(X)):
    for j in range(0,len(Y)):
        C[i,j] = 1/(X[i]-Y[j])
C

array([[-0.25      , -0.33333333, -0.5       , -1.        , -0.14285714,
        -0.33333333, -0.16666667, -1.        ],
       [-0.33333333, -0.5       , -1.        ,         inf, -0.16666667,
        -0.5       , -0.2       ,         inf],
       [-1.        ,         inf,  1.        ,  0.5       , -0.25      ,
                inf, -0.33333333,  0.5       ],
       [-0.25      , -0.33333333, -0.5       , -1.        , -0.14285714,
        -0.33333333, -0.16666667, -1.        ],
       [ 1.        ,  0.5       ,  0.33333333,  0.25      , -0.5       ,
         0.5       , -1.        ,  0.25      ],
       [ 0.33333333,  0.25      ,  0.2       ,  0.16666667,         inf,
         0.25      ,  1.        ,  0.16666667]])

**4) Consider two random array A and B, check if they are equal or not. (Use for loop and if conditions for this problem. Do not use existing codes. Use your own codes). **

In [18]:
# Below are two arrays, we can add or delete values in arrays -
# to test the array comparison code
l = np.array([1,5,2,6,8])
m = np.array([2,6,5,8,1])

In [19]:
len_l = len(l)
len_m = len(m)
cnt = 0
if len_l == len_m:
    for item in l:
        if item in m:
            cnt += 1
    if len_l == cnt:
        print("Arrays are equal.")
    elif len_l != cnt:
        print("Arrays are not equal")
else:
    print("Arrays are not equal.")

Arrays are equal.


**5) How to get the nth largest values of an array? (Use for loop for this problem. Do not use existing codes. Use your own codes).**

In [20]:
#np.random.seed(8)
#arr = np.random.randint(10, size=6)
# Change size above to increase or decrease number of values in an array
#lst = list(arr)
#print("The array is {}".format(lst))

lst = [3, 4, 1, 9, 5, 8]
nth = 2 # Change this value to get nth largest value of an array
j = 0
if nth == 1:
    print("{}st largest value is {}".format(nth, max(lst)))
elif (nth > 1) & (nth <= len(lst)):
    for i in range(0,nth-1):
        ind = lst.index(max(lst))
        del(lst[ind])
    print("{} largest value is {}".format(nth, max(lst)))
elif (nth > len(lst)) or (nth <= 0):
    print("nth value is not valid.")           

2 largest value is 8


**6) Write a Python code which calculates the following equation.(You can take the power as large number , for example 25).**

\begin{align}
\sin(x) & \approx x - \frac{x^3}{3!} + \frac{x^5}{5!} - \frac{x^7}{7!} + \cdots \\
\end{align}    

In [21]:
def factorial(powerNum):
    if powerNum > 1:
        # Below is a recursive programming step
        return powerNum * factorial(powerNum-1) 
    return 1

sine = 0
xNum=2
powerNum=7
for i in range(powerNum):
    sign = (-1)**i
    sine = sine + ((xNum**(2.0*i+1))/factorial(2*i+1))*sign

print(sine)

0.9092974515196738


**Above code can be changed into a Function as below**

In [22]:
# Here xNum is a number and powerNum represent the power of a number i.e. xNum
def sin(xNum,powerNum):
    sine = 0
    for i in range(powerNum):
        sign = (-1)**i
        sine = sine + ((xNum**(2.0*i+1))/factorial(2*i+1))*sign
    return sine

def factorial(powerNum):
    if powerNum > 1:
        # Below is a recursive programming step
        return powerNum * factorial(powerNum-1) 
    return 1

In [659]:
sin(2,7)

0.9092974515196738

**7) Define a Python function which finds the largest even and odd numbers in a list. (Use for loop and if conditions for this problem. Do not use existing codes. Use your own codes).**

In [23]:
myList = [1,4,3,6,7,9]
evenNum = 0
oddNum = 0
for item in myList:
    if (item % 2 is 0) & (item > evenNum):
        evenNum = item
    elif (not item % 2 is 0) & (item > oddNum):
        oddNum = item
        
print("Original list : {}".format(myList))
print("Largest Even Number : {}".format(evenNum))
print("Largest Odd Number : {}".format(oddNum))

Original list : [1, 4, 3, 6, 7, 9]
Largest Even Number : 6
Largest Odd Number : 9


**Above code can be changed into a Function as below**

In [24]:
def getLargestOddEvenNum(numList):
    evenNum = 0
    oddNum = 0
    for item in numList:
        if (item % 2 is 0) & (item > evenNum):
            evenNum = item
        elif (not item % 2 is 0) & (item > oddNum):
            oddNum = item

    print("Original list : {}".format(numList))
    print("Largest Even Number : {}".format(evenNum))
    print("Largest Odd Number : {}".format(oddNum))

In [25]:
myList = [1,4,3,6,7,8]
getLargestOddEvenNum(myList)

Original list : [1, 4, 3, 6, 7, 8]
Largest Even Number : 8
Largest Odd Number : 7


**8) Define a Python function which finds the all of the even numbers and the product of the even numbers.  (Use for loop and if conditions for this problem. Do not use existing codes. Use your own codes).**

In [26]:
myList = [1,4,3,6,7,9]
evenNum = []
prodEvenNum = 1
for item in myList:
    if (item % 2 is 0):
        evenNum.append(item)
        prodEvenNum = prodEvenNum * item

print("Original list : {}".format(myList))
print("All even numbers are : {}".format(evenNum))
print("Product of even numbers : {}".format(prodEvenNum))

Original list : [1, 4, 3, 6, 7, 9]
All even numbers are : [4, 6]
Product of even numbers : 24


**Above code can be changed into a Function as below**

In [27]:
def getEvenNumandProd(numList):
    evenNum = []
    prodEvenNum = 1
    for item in numList:
        if (item % 2 is 0):
            evenNum.append(item)
            prodEvenNum = prodEvenNum * item

    print("Original list : {}".format(numList))
    print("All even numbers are : {}".format(evenNum))
    print("Product of even numbers : {}".format(prodEvenNum))

In [28]:
myList = [1,4,3,6,7,8]
getEvenNumandProd(myList)

Original list : [1, 4, 3, 6, 7, 8]
All even numbers are : [4, 6, 8]
Product of even numbers : 192
