In [34]:
from IPython.display import HTML

# HW3 Working with NumPy and SciPy in Python

NumPy and SciPy are open source modules for Python, which provide fast precompiled functions for mathematical and numerical routines. NumPy is an acronym for "Numeric Python" or "Numerical Python" and SciPy is an acronym for "Scientific Python".

## <u><b>1. NumPy</b></u>

NumPy or "Numerical Python" module makes Python programming language more powerful with its powerful data structures for efficient computation of multi-dimensional arrays and matrices.

Below are some examples to understand how to work with NumPy in Python:

### Importing NumPy

In [35]:
import numpy as np # We need to import NumPy to use in our program. We use import keyword to import any module in python

# np is used as alias and we see it always when we see any program where NumPy is being imported.

### Arrays

Main feature of NumPy is an Array object. Arrays are similar to List however the data type of all elements of array should be same. Arrays are much fast for calculation.

In [36]:
#  Below we can see that the function array takes two arguments: the list to be converted into the array and the type of each member of the list.

arr = np.array([10,20,30,40,50], int) # Here we are creating a NumPy array from a list of some numbers.

print(type(arr)) # we can now check the class of a variable to know if it is an array or some other type of class.

<class 'numpy.ndarray'>


We do operations on Arrays just like we do on Lists.

In [37]:
arr[2] # Accessing array elements

30

In [38]:
arr[1] = 100 # Updating array element
arr

array([ 10, 100,  30,  40,  50])

In [39]:
arr.shape # The shape property of an array returns a tuple with the size of each array dimensions.

# Here we created only one dimensional array with size 5

(5,)

In [40]:
arr.dtype # The dtype property can be used to know what type of values are stored by the array.

dtype('int32')

In [41]:
 # The copy function is used to create a separate copy of an array in memory.
arr1 = np.array([1, 2, 3, 4, 5, 6], float)
carr = arr1.copy() # Copying an array to new variable
carr[1] # Accessing elements from newly copied array

2.0

In [42]:
# We can fill an array with a single value.
arr2 = np.array([1, 2, 3, 4, 5, 6], float)
arr2.fill(1) # Filling array with 1 which will replace eralier values from array
arr2

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
#  We can increase the dimensionality of an array using the newaxis constant notation in bracket like below:
arr3 = np.array([1, 2, 3, 4, 5], int) # One dimensional array
arr4 = arr3[:,np.newaxis] # adding another dimension using np.newaxis
arr4.shape # checking the dimensions

(5, 1)

### Iteration through Array

In [44]:
arr5 = np.array([10, 20, 30], int)
for ar in arr5: # iterating through array using for loop
    print(ar)

10
20
30


### Basic Array Operations

In [45]:
# Taking Sum of an array
arr6 = np.array([10, 20, 30], int)
print(arr6.sum()) # Using Sum function to get sum of an array

60


In [46]:
# Taking Mean of an array
arr7 = np.array([10, 20, 30], int)
print(arr7.mean()) # Using Mean function to get mean of an array

20.0


In [47]:
# Taking Min of an array
arr7 = np.array([10, 20, 30], int)
print(arr7.min()) # Using Min function to get min of an array

10


In [48]:
# Taking Max of an array
arr7 = np.array([10, 20, 30], int)
print(arr7.max()) # Using Max function to get max of an array

30


In [49]:
# Sorting an array
arr8 = np.array([1, 20, 3, 45, 10, 6], int)
arr8.sort() # Using Sort function to sort elements of an array
print(arr8)

[ 1  3  6 10 20 45]


### Generating Random Numbers

In [50]:
# First we will set a seed so whenever we generate random number, we get same numbers
np.random.seed(123) # Setting a seed
np.random.rand(5) # Generating random numbers using Rand function

array([ 0.69646919,  0.28613933,  0.22685145,  0.55131477,  0.71946897])

In [51]:
np.random.random() # Use random() function generate only one single random number between 0.0 and 1.0

0.42310646012446096

In [52]:
np.random.normal(1, 1.5, size = 5) # Generating 5 random number with normal distribution using mean as 1 and standard deviation as 1.5


array([-2.64001887,  0.35663106,  2.89890439, -0.3001106 , -0.01832923])

In [53]:
np.random.normal(size = 5) # If we omit the arguments mean and sd then we get the numbers with mean = 0 and standard deviation = 1

array([-0.09470897,  1.49138963, -0.638902  , -0.44398196, -0.43435128])

## <u><b>2. SciPy</b></u>

The SciPy or "Scientific Python" module extends the functionality of NumPy with a substantial collection of useful algorithms, like minimization, Fourier transformation, regression, and other applied mathematical techniques.

SciPy is organized into subpackages covering different scientific computing domains. These are summarized in the following table:

<b>cluster - </b>	         <i>Clustering algorithms</i>

<b>constants - </b>	     <i>Physical and mathematical constants</i>

<b>fftpack - </b>	         <i>Fast Fourier Transform routines</i>

<b>integrate - </b>	     <i>Integration and ordinary differential equation solvers</i>

<b>interpolate - </b>	     <i>Interpolation and smoothing splines</i>

<b>io - </b>	             <i>Input and Output</i>

<b>linalg - </b>	         <i>Linear algebra</i>

<b>ndimage - </b>	         <i>N-dimensional image processing</i>

<b>odr - </b>	             <i>Orthogonal distance regression</i>

<b>optimize - </b>	         <i>Optimization and root-finding routines</i>

<b>signal - </b>	         <i>Signal processing</i>

<b>sparse - </b>	         <i>Sparse matrices and associated routines</i>

<b>spatial - </b>	         <i>Spatial data structures and algorithms</i>

<b>special - </b>	         <i>Special functions</i>

<b>stats - </b>	         <i>Statistical distributions and functions</i>

Below are some examples to understand how to work with SciPy in Python:

### Importing SciPy and its sub modules

In [54]:
# We need to import SciPy and its sub modules to use in our program.
import scipy as sp # Importing SciPy as alias sp
from scipy import * # Importing all sub modules
from scipy import linalg # Importing Linear Algebra submodule
from scipy.stats import linregress # Here we are importing Linear Regression function from stats submodule

### Simple Linear Regression using SciPy Stats submodule



In [55]:
x = np.random.randn(100)
y = 3 * x + 0.2 * np.random.randn(100)
gradient, intercept, r_value, p_value, std_err = linregress(x, y)
print("Slope = ", gradient, " and ", "Intercept = ", intercept) # Here we are printing slope and intercept values

Slope =  3.01495104174  and  Intercept =  -0.00222573526478


### Finding Inverse Matrix

In [56]:
A = mat('[1 3 5; 2 5 1; 2 3 8]') # Creating a matrix
A
linalg.inv(A) # getting inverse matrix, we can also use A.I

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

### Getting Help

In [57]:
# When scipy.info() is given a string argument, it does a search for matching objects. It returns documentation specific to that object.
sp.info("gamma")

     *** Found in numpy.random ***
gamma(shape, scale=1.0, size=None)

Draw samples from a Gamma distribution.

Samples are drawn from a Gamma distribution with specified parameters,
`shape` (sometimes designated "k") and `scale` (sometimes designated
"theta"), where both parameters are > 0.

Parameters
----------
shape : float or array_like of floats
    The shape of the gamma distribution. Should be greater than zero.
scale : float or array_like of floats, optional
    The scale of the gamma distribution. Should be greater than zero.
    Default is equal to 1.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is returned if ``shape`` and ``scale`` are both scalars.
    Otherwise, ``np.broadcast(shape, scale).size`` samples are drawn.

Returns
-------
out : ndarray or scalar
    Drawn samples from the parameterized gamma distribution.

See Als

### Constant Sub-module

The constants sub-module contains a wide variety of physical constants. Few examples are given below:

In [58]:

from scipy import constants

constants.c # speed of light

299792458.0

In [59]:
constants.h # Plank’s constant

6.62607004e-34